# vue的错误处理机制

1.   默认情况下，如果全局的 config.errorHandler 被定义，所有的错误仍会发送它，因此这些错误仍然会向单一的分析服务的地方进行汇报。

2.  如果一个组件的继承或父级从属链路中存在多个 errorCaptured 钩子，则它们将会被相同的错误逐个唤起。

3.  如果此 errorCaptured 钩子自身抛出了一个错误，则这个新错误和原本被捕获的错误都会发送给全局的 config.errorHandler。

4.  一个 errorCaptured 钩子能够返回 false 以阻止错误继续向上传播。本质上是说“这个错误已经被搞定了且应该被忽略”。它会阻止其它任何会被这个错误唤起的 errorCaptured 钩子和全局的 config.errorHandler。

> 如下的代码片段可以看到，一个组件内部抛出错误后，自身及父组件链路上所有的errorCapture hook都会执行。最后config.errorHandler也会执行。

* main.js
``` javascript
Vue.config.errorHandler = function (err, vm, info) {
    console.error('global error')
}
```

* sourceErrComponent.vue
``` javascript
<template>
    <div>
        <h1>hello i'm parent</h1>
        <div>
            <h2>provided props: name => {{_provided.parentName}}</h2>
            <Child/>
        </div>
    </div>
</template>

<script>
export default {
    components: {
        'Child': {
            components: {
                inject: {
                    injectName: {
                        from: 'parentName',
                        default: 'unknown'
                    }
                },
                'SubChild': {
                     template: `
                        <div>
                            <h4>Hello i'm subChild</h4>
                            <div>
                                <h3>My name: {{this.injectName }}</h3>
                            </div>
                        </div>
                    `,
                    mounted () {
                        throw new Error('custom error')
                    },
                    errorCaptured (e,a,b,c,d) {
                        console.log(e,a,b,c,d)
                    }
                }
            },
            inject: {
                injectName: {
                    from: 'parentName',
                    default: 'unknown'
                }
            },
            created: function () {
            },
            template: `
                <div>
                    <h3>Hello i'm child</h3>
                    <div>
                        <h3>My name: {{this.injectName }}</h3>
                        <SubChild/>
                    </div>
                </div>
            `, errorCaptured (e,a,b,c,d) {
                        console.log(e,a,b,c,d)
                    }
        }
    },
    mounted () {
        setTimeout(function () {
             // error
            // this._provided.parentName = 'skybbb'
        }, 1000)
    },
    provide: {
        parentName: 'skyyy'
    },
    data: function () {
        return {
            name: 'sky'
        }
    },
     errorCaptured (e,a,b,c,d) {
        console.log(e,a,b,c,d)
    }
}
</script>
```